apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: api-ia-web
type: Opaque
stringData:
  GOOGLE_API_KEY: "COLOQUE_SUA_GOOGLE_API_KEY_AQUI"
  JWT_SECRET: "uma_chave_grande_secreta_para_desenvolvimento"
