api/Version: apps/v1
kind: Deployment
metadate:
  name: backend-deployment
spec: 
  replicas: 2 # Executa 2 instâncias do backend para alta disponibilidade
  selector:
    matchLabels:
      app: backend
    template:
      metadata:
        labels:
          app: backend
      spec:
        containers:
          -name: backend
          image: toikano/api_gemini_docker-backend:latest
          ports:
            -containerPort: 5173
          env:
            -name: NODE_ENV
            value: "production"
            
