api/Version: apps/v1
kind: Deployment
metadate:
  name: frontend-deployment
spec: 
  replicas: 2 # Executa 2 instâncias do frontend para alta disponibilidade
  selector:
    matchLabels:
      app: frontend
    template:
      metadata:
        labels:
          app: frontend
      spec:
        containers:
          -name: frontend
          image: toikano/api_gemini_docker-frontend:latest
          ports:
            -containerPort: 5000
          env:
            -name: NODE_ENV
            value: "production"
            