apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: sistema
type: Opaque
stringData:
  GEMINI_API_KEY: "sua_chave_aqui"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_NAME: "users_ia_api"
