services:
  frontend:
    build:
      context: ./src/frontend
    container_name: vite_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    depends_on:
      - api
    command: npm run dev
  api:
    build: 
      context: ./src/backend
    container_name: api_gemini_backend_banco
    env_file:
      - .env
    volumes:
      - ./src/backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    command: npm run dev

  db:
    image: postgres:16
    container_name: api_gemini_db
    env_file:
      - .env
    volumes:
      -  postgres_data:/var/lib/postgresql/data
      - ./src/backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d meubanco"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
volumes:
  postgres_data: